apiVersion: v1
kind: Secret
metadata:
  name: db-write-service-secrets
type: Opaque
stringData:
  KAFKA_BROKERS: "10.244.0.7:9092"
  KAFKA_TOPIC: "stock-quotes"
  MINIO_ENDPOINT: "10.244.0.9:9000"
  MINIO_ACCESS_KEY: "username"
  MINIO_SECRET_KEY: "password"