apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-write-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-write-service
  template:
    metadata:
      labels:
        app: db-write-service
    spec:
      imagePullSecrets:
      - name: ghcr-creds
      containers:
      - name: db-write-service
        image: ghcr.io/quantlytic/dbwriteservice:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"