apiVersion: v1
kind: Service
metadata:
  name: db-write-service
spec:
  selector:
    app: db-write-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-write-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-write-service
  template:
    metadata:
      labels:
        app: db-write-service
    spec:
      containers:
      - name: db-write-service
        image: db-write-service:latest # Replace with your image registry
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20