# Builder stage
FROM golang:1.24.5 AS builder

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./
# Download dependencies
RUN go mod download

# Copy all source code
COPY . .

# Build the application as a static binary
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/server .

# Final stage
FROM scratch

WORKDIR /

# Copy the binary from the builder stage
COPY --from=builder /app/server .

# Run the binary
CMD ["/server"]