# Builder
FROM golang:1.24.5 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# CGO must be enabled for confluent-kafka-go
ENV CGO_ENABLED=1
RUN go build -o /app/server .

# Final image with dependencies
FROM debian:bookworm-slim

# Install librdkafka runtime dependencies
RUN apt-get update && apt-get install -y \
    librdkafka1 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /

COPY --from=builder /app/server .

CMD ["/server"]
